{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "34f25feb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import win32com.client\n",
    "import pythoncom\n",
    "import time\n",
    "import os\n",
    "\n",
    "def Plotear_A1():\n",
    "\n",
    "    # PARA CONECTAR CON AUTOCAD\n",
    "    acad = win32com.client.Dispatch(\"AutoCAD.Application\")\n",
    "    doc = acad.ActiveDocument\n",
    "\n",
    "    # NOMBRE DEL ARCHIVO \n",
    "    nombre_dwg = doc.Name\n",
    "    nom = nombre_dwg[:-4]   \n",
    "\n",
    "    # RUTA DE SALIDA \n",
    "    ruta = r\"C:\\Users\\....\\....\\....\" # <<< AQUI DEBEN PONER LA DIRECCION DE LA CARPETA DONDE GUARDARAN LOS PDFS\n",
    "    os.makedirs(ruta, exist_ok=True)\n",
    "\n",
    "    # FORZAR LAYOUT DE PAPEL \n",
    "    doc.ActiveLayout = doc.Layouts.Item(\"Layout1\") # <<< AQUI DEBEN PONER EL NOMBRE DEL LAYOUT, POR DEFECTO \"Layout1\"\n",
    "    layout = doc.ActiveLayout\n",
    "\n",
    "    #  LIMPIAR SELECTION SET \n",
    "    try:\n",
    "        doc.SelectionSets.Item(\"SS1\").Delete()\n",
    "    except:\n",
    "        pass\n",
    "\n",
    "    ss = doc.SelectionSets.Add(\"SS1\")\n",
    "    ss.SelectOnScreen()\n",
    "\n",
    "    contador = 1\n",
    "\n",
    "    for ent in ss:\n",
    "\n",
    "        if ent.EntityName != \"AcDbPolyline\":\n",
    "            continue\n",
    "\n",
    "        #  BOUNDING BOX \n",
    "        coords = ent.Coordinates\n",
    "\n",
    "        x = coords[0::2]\n",
    "        y = coords[1::2]\n",
    "\n",
    "        xmin, xmax = min(x), max(x)\n",
    "        ymin, ymax = min(y), max(y)\n",
    "\n",
    "        P1 = win32com.client.VARIANT(\n",
    "            pythoncom.VT_ARRAY | pythoncom.VT_R8, (xmin, ymin)\n",
    "        )\n",
    "        P2 = win32com.client.VARIANT(\n",
    "            pythoncom.VT_ARRAY | pythoncom.VT_R8, (xmax, ymax)\n",
    "        )\n",
    "\n",
    "        # ARCHIVO PDF \n",
    "        plotfile = os.path.join(ruta, f\"{nom}-{contador}.pdf\")\n",
    "\n",
    "        # CONFIGURACIÓN PARA EL PLOTEO \n",
    "        layout.ConfigName = \"DWG To PDF.pc3\"\n",
    "        layout.CanonicalMediaName = \"ISO_full_bleed_A1_(841.00_x_594.00_MM)\"\n",
    "        layout.PaperUnits = 1\n",
    "        layout.PlotRotation = 0\n",
    "        layout.StyleSheet = \"None\" # <<< AQUI DEBEN PONER SU \"PLOT STYLE TABLE\" (SI LO TIENEN)\n",
    "\n",
    "        layout.PlotType = 4  # acWindow\n",
    "        layout.SetWindowToPlot(P1, P2)\n",
    "\n",
    "        layout.UseStandardScale = False\n",
    "        layout.SetCustomScale(1, 1)\n",
    "        layout.StandardScale = 0\n",
    "\n",
    "        # REFRESCAR AUTOCAD \n",
    "        doc.SetVariable(\"BACKGROUNDPLOT\", 0)\n",
    "        doc.SetVariable(\"PLOTOUTPUTOPEN\", 0)  # <<< ES PARA EVITAR QUE SE ABRAN LOS PDF, SI QUIEREN QUE SE ABRAN COMO EN EL VIDEO LE PONEN \"1\"\n",
    "        doc.Regen(1)\n",
    "        time.sleep(0.3)\n",
    "\n",
    "        # CENTRAR Y PLOTEAR \n",
    "        layout.CenterPlot = True\n",
    "        doc.Plot.PlotToFile(plotfile)\n",
    "\n",
    "        contador += 1\n",
    "        time.sleep(1)\n",
    "\n",
    "    print(\"✔ PDFs generados correctamente\")\n",
    "\n",
    "def main():\n",
    "    Plotear_A1()\n",
    "\n",
    "main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b0c35c5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
